# -*- coding: utf-8 -*-
"""Early Cancer Diagnosis by Year

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLZUizLt-zuL8EJKJRS5OaF0EVyV_vGa
"""

import pandas as pd

import matplotlib.pyplot as plt

df = pd.read_csv("/content/cancers-diagnosed-at-stage-1-or-2-chart-data.csv")

print(df.head())

print(df.describe())

df["Yearly Change"] = df["England Value"].diff()

print(df[["Time period","Yearly Change"]])

# Plot
plt.figure(figsize=(10,6))

plt.plot(df.iloc[:,0], df.iloc[:,1], marker="o")

plt.title("Early Stage Cancer Diagnosis in England")
plt.xlabel("Year")
plt.ylabel("Percentage Diagnosed at Stage 1 or 2")

plt.grid(True)
plt.show()

plt.figure(figsize=(12,6))

plt.plot(df.iloc[:,0], df.iloc[:,1], marker='o')

plt.title("Trend in Early Cancer Diagnosis in England (2013–2022)", fontsize=14)
plt.xlabel("Year")
plt.ylabel("Percentage Diagnosed at Stage 1 or 2")

plt.xticks(rotation=45)

plt.grid(True)

plt.show()